In [1]:
import numpy as np

In [2]:
def vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    result = 0.0
    for i in range(u.shape[0]):
        result = result + u[i]*v[i]

    return result

In [3]:
u = np.array([1,2,3,5])

In [4]:
v = np.array([2,3,4,6])

In [5]:
vector_multiplication(u,v)

np.float64(50.0)

In [6]:
u.dot(v)

np.int64(50)

Mtrix-vector multiplication

In [7]:
U =np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [33]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [2,1,0],
    [3,0,2]
])

In [15]:
U.shape[1]

4

In [16]:
def matrix_vector_multiplication(u,v):
    assert u.shape[1] == v.shape[0]

    num_rows = u.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
       result[i] = vector_multiplication(u[i],v)
    return result

In [17]:
matrix_vector_multiplication(U,v)

array([72., 24., 23.])

In [18]:
U.dot(v)

array([72, 24, 23])

In [31]:
def matri_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        result[:,i] = matrix_vector_multiplication(U,V[:,i])
        
    return result

In [35]:
matri_matrix_multiplication(U,V)

array([[30. ,  9. , 10. ],
       [ 9. ,  3. ,  5.5],
       [20. ,  8. ,  9. ]])