In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(5,5)

array([5, 5, 5, 5, 5])

In [5]:
a = np.array([1,3,5,6,4,8])
a

array([1, 3, 5, 6, 4, 8])

In [6]:
a[2]=10

In [7]:
a

array([ 1,  3, 10,  6,  4,  8])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,2,11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [11]:
np.array([[1,2],[2,1]])

array([[1, 2],
       [2, 1]])

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
n = np.array([
     [1,2,3],
     [3,4,5],
     [7,8,9]
])
print(n)

[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [14]:
n[0, 1] = 20

In [15]:
print(n)

[[ 1 20  3]
 [ 3  4  5]
 [ 7  8  9]]


In [16]:
n[0]=[1,1,1]

In [17]:
n

array([[1, 1, 1],
       [3, 4, 5],
       [7, 8, 9]])

In [18]:
n[:,1]=[2,2,2]
n

array([[1, 2, 1],
       [3, 2, 5],
       [7, 2, 9]])

randomly generated arrays

In [19]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [20]:
np.random.seed(2)
np.random.randn(5,2) #标准正态分布中提取

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [21]:
np.random.seed(2)
np.random.randint(low=0, high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

Element-wise operations

In [22]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
b=(10 + (a*2))**2/100

In [24]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [25]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

Comparison operations

In [26]:
a

array([0, 1, 2, 3, 4])

In [27]:
a >= 2

array([False, False,  True,  True,  True])

In [28]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [29]:
a > b

array([False, False,  True,  True,  True])

In [30]:
a1 = np.array([
    [1,2],
    [3,4]
])
b1 = np.array([
    [0,1],
    [9,9]
])

In [31]:
a1 >= 4

array([[False, False],
       [False,  True]])

In [32]:
a1 >= b1

array([[ True,  True],
       [False, False]])

In [34]:
a.min()

np.int64(0)

In [35]:
a.std()

np.float64(1.4142135623730951)